title: Empty Attic
email: Rolo@email.com
description: >- # this means to ignore newlines until "baseurl:"
  I consider that a man's brain originally is like a little empty attic, 
  and you have to stock it with such furniture as you choose.

url: "https://dashvvood.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/jekyll-blog" # the subpath of your site, e.g. /blog

# twitter_username: jekyllrb
github_username:  Dashvvood

# Build settings
theme: minima
# remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

markdown: kramdown

